const {readFileSync} = require('node:fs');
const {runInNewContext} = require('node:vm');
const assert = require('node:assert/strict');
const html = readFileSync('web/audiobook/index.html','utf8');
const source = readFileSync('web/audiobook/app.js','utf8');
const elements=Object.fromEntries([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],{setAttribute(name,value){this[name]=value;}}]));
const context={document:{getElementById:id=>elements[id]},Date};
runInNewContext(source.split('let current =')[0], context);
context.activity({sampled_at:Date.now()/1000,cpu_percent:25,gpu:{name:'GPU',utilization:75,memory_used:4096,memory_total:8192,temperature:60},cores:[{name:'cpu0',percent:50}],memory:{used:1073741824,total:2147483648,available:1073741824,percent:50,swap_used:0,swap_total:0},processes:[{pid:1,name:'python',cpu_percent:120,rss:1048576}]});
assert.equal(elements['cpu-load'].textContent,'25.0%');
assert.equal(elements['gpu-load'].textContent,'75.0%');
assert.equal(elements['ram-load'].textContent,'50.0%');
assert.match(elements['cpu-cores'].textContent,/cpu0.*50%/);
assert.match(elements['process-list'].textContent,/120.0.*python/);
assert.ok(elements['gpu-trend'].points);
context.activity(null);
assert.equal(elements['cpu-load'].textContent,'Unavailable');
assert.equal(elements['ram-load'].textContent,'Unavailable');
assert.equal(elements['gpu-trend'].points,'');
assert.equal(elements['process-list'].textContent,'Process readings unavailable');
console.log('Workspace monitor rendering and unavailable-state checks passed.');

const diffContext = {};
runInNewContext(source.slice(source.indexOf('const escapeHtml'), source.indexOf('function setView')) + source.slice(source.indexOf('function diffMarkup'), source.indexOf('function renderReview')), diffContext);
assert.equal(diffContext.diffMarkup([{text:'<script>',changed:true},{text:' & safe',changed:false}], ''), '<mark>&lt;script&gt;</mark> &amp; safe');
console.log('Review highlighting safely escapes transcript text.');
